name: Automatic Approve
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  automatic-approve:
    name: Automatic Approve
    runs-on: ubuntu-latest
    steps:
      - name: Automatic Approve
        uses: mheap/automatic-approve-action@v1
        with:
          token: ${{ secrets.SECRET_PAT }}
          workflows: "policy.yml"
