# This is a basic workflow to help you get started with Actions

name: vaildate-HW1

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  vaildate-HW1:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      repository-projects: write
    steps:
      - uses: hmarr/auto-approve-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: deepakputhraya/action-pr-title@master
        with:
          regex: "HW-01-[a-z]{3}[0-9]{6}" # Regex the title should match.
      - uses: actions/checkout@v3
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.2.0
      - name: validate
        run: make all
