# This is a basic workflow to help you get started with Actions

name: Create cluster

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  create-cluster:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.2.0
      - name: docker  pull
        run: docker pull nginx:latest
      - name: kind load
        run: kind load docker-image nginx:latest --name chart-testing
      - name: kubectl apply
        run: kubectl apply -f manifest
      - name: kubectl get
        run: |
          for i in {1..5}
          do
            kubectl get pod -A          
            sleep 5s
          done
      - name: curl
        run: |
          export cid=`docker ps -q`
          echo $cid
          export nodeport=`kubectl get svc banana-service -o jsonpath='{.spec.ports[0].nodePort}'`
          echo $nodeport
          docker exec $cid curl 127.0.0.1:$nodeport
