name: Block Merge Based on Time
on:
  pull_request:
    types:
      - opened
      - reopened

jobs:
  block:
    runs-on: ubuntu-latest
    steps:
      - uses: deepakputhraya/action-pr-title@master
        with:
          regex: '([a-z])+\/([a-z])+' # Regex the title should match.
      - uses: yykamei/block-merge-based-on-time@v1
        with:
          timezone: Asia/Taipei
          prohibited-days-dates: "2022-06-04/2022-06-10"
