name: Close PR on files which are not allowed to edit

on:
  pull_request_target:
    types: [opened, reopened]
    paths:
      - "Makefile"
      - ".github/workflows/*"

jobs:
  close-pr:
    runs-on: "ubuntu-latest"
    permissions:
      pull-requests: write
      repository-projects: write
    steps:
      - uses: hmarr/auto-approve-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: superbrothers/close-pull-request@v3
        with:
          comment: "hi. please do not touch 'Makefile' and '.github/workflows/*'."
